### PR TITLE
Drug response

### PR DESCRIPTION
**Pull request by prismofeverything**
Broke drug response widget out into its own page.

### CODE REVIEW

**Comment by kellrott** [comment]
Do you want to merge to dev now? Or wait till working?

**Comment by kellrott** [comment]
In testing, this page seems much slower than previously seen

**Comment by prismofeverything** [comment]
Agreed, not sure why it is so slow, since nothing has really changed. There
are a couple suspects:

* It has always been a bit slower on bmeg.io, and we just got reports they
are utilizing their cluster even more lately.
* It is a large amount of data returned, so maybe shunting it all through
the proxy again makes it drag.
* There are more variants on bmeg.io, so the query could be taking longer
(though this one is undermined by the widget taking a reasonable amount of
time when deployed on the site).

Maybe it is a fourth option. Anything else come to mind?

My approach now is going to be adding a vertex-centric index on the edge
between Variant and Gene, as well as upgrading the bmeg.io server to a
larger one (currently underway).

**Comment by prismofeverything** [comment]
There could be something else which just came to mind. We switched out the
library we were using for the browser fetch, which may be interfering.

This one is a long shot, but something to check out anyway and a
possibility if we are being thorough.

**Comment by kellrott** [comment]
Is the sample selection https://github.com/bmeg/bmeg-proxy/blob/drug-response/src/js/bmeg/response.jsx#L124 ? 
If that is the case, it traveling onto TCGA samples before being eliminated. That would cause a huge slowdown.

**Comment by prismofeverything** [comment]
Agreed, though that is the same query that is currently running in
production, which exhibits reasonable time. This makes me feel like it is
something to do with the proxy.

This is supported by running the exact same query in the python client,
which returns without delay.

That said, we could optimize this query by putting the cohort on the edge
between samples and variants like you say. This would be the perfect use of
a vertex-centric index. We will probably have to as we continue to add more
data to the system.

**Pull request merged**
